<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Archive\Enums;

/**
 * Defines the supported primary key types for database models.
 *
 * This enum specifies the three primary key strategies available for Eloquent
 * models: traditional auto-incrementing IDs, ULIDs (Universally Unique
 * Lexicographically Sortable Identifiers), and UUIDs (Universally Unique
 * Identifiers). Each type has specific use cases and trade-offs regarding
 * sortability, uniqueness guarantees, and database compatibility.
 *
 * @author Brian Faust <brian@cline.sh>
 */
enum PrimaryKeyType: string
{
    /**
     * Traditional auto-incrementing integer primary key.
     *
     * Sequential numeric IDs generated by the database. Efficient for indexing
     * and sorting but may expose record counts and creation order.
     */
    case ID = 'id';

    /**
     * Universally Unique Lexicographically Sortable Identifier.
     *
     * 26-character case-insensitive string that encodes timestamp information,
     * enabling chronological sorting while maintaining uniqueness guarantees.
     * Preferred for distributed systems requiring time-ordered identifiers.
     */
    case ULID = 'ulid';

    /**
     * Universally Unique Identifier (version 4).
     *
     * 36-character string (32 hex digits with hyphens) providing strong
     * uniqueness guarantees across distributed systems. Does not encode
     * temporal information, making it unsuitable for time-based sorting.
     */
    case UUID = 'uuid';
}
